version: '3.9'

services:
  db:
    image: postgres:16
    container_name: students-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: students-api
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_DOCKER_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data: